### ISSUE TITLE
Evaluation for BBH

### ISSUE THREAD

**Issue by ZLKong** [18907305772/FuseAI#20]
Hi, 

I used the BBH code that you referenced https://github.com/allenai/open-instruct/blob/main/scripts/eval/bbh.sh

However, I could not get the exact results of the paper. 

For example, when running llama-7b, the results looks like:
```
    "dyck_languages": 0.1,
    "temporal_sequences": 0.125,
    "sports_understanding": 0.875,
    "logical_deduction_five_objects": 0.25,
    "boolean_expressions": 0.725,
```

My question is:
1. How to get non .x5, .xx5 results as in paper (e.g. temporal_sequences: 28.08)？
2. Although total average results are similar with the paper, but each individual results are very different. It might be due to the settings, such as using n-shot, CoT, etc. Could you please share the detailed settings or scripts for running the bbh?

Thank you very much!

**Comment by 18907305772** [comment]
1. Please do not use vLLM for evaluation, which results in lower performance.
2. Please do not set `max_num_examples_per_task`, which results in the .x5 in the results.

**Comment by ZLKong** [comment]
Thank you very much!
